name: upscalergui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  window_manager: ^0.3.2
  google_fonts: ^4.0.4
  toggle_switch: ^2.1.0
  file_picker: ^5.2.11
  image_compare_slider: ^2.7.0
  process_run: ^0.13.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256 
 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
 
  